export const TEXT_INPUT_CHANGED = 'TEXT_INPUT_CHANGED'
export const SUBMIT_BUTTON_PRESSED = 'SUBMIT_BUTTON_PRESSED'
export const HELP_BUTTON_PRESSED = 'HELP_BUTTON_PRESSED'
export const AUDIO_BUTTON_PRESSED = 'AUDIO_BUTTON_PRESSED'
